---
- name: Generate / Renew SSL certificates
  hosts: aws
  become: true
  tasks:
    - name: Copy the shell script to the remote server
      ansible.builtin.copy:
        src: ./cert_generator.sh
        dest: /tmp/cert_generator.sh
        mode: "0755"

    - name: Execute the shell script on the remote server
      ansible.builtin.shell: /tmp/cert_generator.sh
      args:
        executable: /bin/bash
        creates: "{{ cert_path }}.tar.gz"
      environment:
        EMAIL_ADDRESS: "{{ mail_address }}"
        DOMAIN: "{{ domain }}"
        CERT_PATH: "{{ cert_path }}"
        EXPIRY_DAYS: "{{ expiry_days }}"
      register: script_output
      failed_when: script_output.rc != 0

    - name: Fetch files
      ansible.builtin.fetch:
        src: /tmp/certs.tar.gz
        dest: build
